
version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        ports: 
          - "8000:8000"
        volumes:
          - ./source/DesafioAPI:/app
          - ./data:/data